version: '3.8'

services:
  # База данных PostgreSQL
  gymdesk-db:
    image: postgres:15-alpine
    container_name: gymdesk-postgres
    restart: always
    environment:
      POSTGRES_DB: gymdesk_db
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend API
  gymdesk-api:
    build:
      context: .
      dockerfile: src/GymDesk.API/Dockerfile
    container_name: gymdesk-api
    restart: always
    depends_on:
      - gymdesk-db
    environment:
      ConnectionStrings__DefaultConnection: "Host=gymdesk-db;Port=5432;Database=gymdesk_db;Username=gym_user;Password=gym_pass_123"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "7200:80"

volumes:
  pgdata: